apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: visitorsapps.operator.k8s.local
spec:
  group: operator.k8s.local
  names:
    kind: VisitorsApp
    listKind: VisitorsAppList
    plural: visitorsapps
    singular: visitorsapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VisitorsApp is the Schema for the visitorsapps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VisitorsAppSpec defines the desired state of VisitorsApp
          properties:
            size:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: int32
              type: integer
            title:
              type: string
          required:
          - size
          - title
          type: object
        status:
          description: VisitorsAppStatus defines the observed state of VisitorsApp
          properties:
            backendImage:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            frontendImage:
              type: string
          required:
          - backendImage
          - frontendImage
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
